-- Add metadata to support comment editing and hiding
ALTER TABLE comments
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS edited_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS edited_by UUID NULL REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS hidden_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS hidden_by UUID NULL REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE comment_attachments
  ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS hidden_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS hidden_by UUID NULL REFERENCES users(id) ON DELETE SET NULL;
